"""Add instrument models

Revision ID: 984924fa0dc7
Revises: fed2c8678058
Create Date: 2025-04-29 22:35:46.680538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '984924fa0dc7'
down_revision = 'fed2c8678058'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instrument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('GUITAR', 'PIANO', 'DRUM', 'VIOLIN', name='instrumenttype'), nullable=False),
    sa.Column('category', sa.Enum('ELECTRIC', 'ACOUSTIC', 'CLASSICAL', 'DIGITAL', 'KEYBOARD', name='instrumentcategory'), nullable=False),
    sa.Column('instrument_type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('electric_drum',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num_pads', sa.Integer(), nullable=False),
    sa.Column('num_cymbals', sa.Integer(), nullable=False),
    sa.Column('has_kick', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guitar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num_strings', sa.Integer(), nullable=False),
    sa.Column('body_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('piano',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num_keys', sa.Integer(), nullable=False),
    sa.Column('is_weighted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('violin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(length=20), nullable=False),
    sa.Column('bow_included', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('violin')
    op.drop_table('piano')
    op.drop_table('guitar')
    op.drop_table('electric_drum')
    op.drop_table('instrument')
    # ### end Alembic commands ###
