"""Initial migration

Revision ID: dc0774421d9d
Revises: 
Create Date: 2025-05-19 22:33:43.606867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc0774421d9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instrument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('GUITAR', 'PIANO', 'DRUM', 'VIOLIN', name='instrumenttype'), nullable=False),
    sa.Column('category', sa.Enum('ELECTRIC', 'ACOUSTIC', 'CLASSICAL', 'DIGITAL', 'KEYBOARD', name='instrumentcategory'), nullable=False),
    sa.Column('instrument_type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('drum',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num_pads', sa.Integer(), nullable=False),
    sa.Column('num_cymbals', sa.Integer(), nullable=False),
    sa.Column('has_kick', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guitar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num_strings', sa.Integer(), nullable=False),
    sa.Column('body_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('piano',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num_keys', sa.Integer(), nullable=False),
    sa.Column('is_weighted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('violin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(length=20), nullable=False),
    sa.Column('bow_included', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('violin')
    op.drop_table('piano')
    op.drop_table('guitar')
    op.drop_table('drum')
    op.drop_table('user')
    op.drop_table('instrument')
    # ### end Alembic commands ###
